spring:
  application:
    name: gateway-spring

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#          这个控制大小写服务ID只影响 gateway 自动配置的路由。
          lowerCaseServiceId: true
      routes:
        - id: custom-route-service
#        这里的服务ID可以使用小写，为什么？
          uri: lb://eureka-client-hello
          predicates:
            - Path=/gateway-service/**
          filters:
            - StripPrefix=1
        - id: custom-route-hostname
#        这里的uri要对应到 eureka 中已经注册的服务名
          uri: lb://localhost
          predicates:
            - Path=/gateway-hostname/**
          filters:
            - StripPrefix=1

server:
  port: 48761

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18761/eureka/





