spring:
  application:
    name: eureka-server

server:
  port: 8762

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


#标记自己是 eureka server，将 registerWithEureka 和 fetchRegistry 置为false。