spring:
  application:
    name: eureka-server

server:
  port: 18761

eureka:
  instance:
    hostname: localhost

#服务端的该设置并不能让所有的客户端注册为IP地址的形式
    prefer-ip-address: true

  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


#标记自己是 eureka server，将 registerWithEureka 和 fetchRegistry 置为false。