spring:
  application:
    name: eureka-client-hello

server:
  port: 18762

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#不使用默认的端口，防止即使没有配置eureka注册中心地址，也依旧按照默认的地址去注册服务的问题
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
