spring:
  application:
    name: customer-feign-hystrix

server:
  port: 28764

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18761/eureka/

feign:
  hystrix:
    enabled: true
#Feign是自带断路器的，在D版本的Spring Cloud之后，它没有默认打开。需要在配置文件中配置打开它。
